export const bibleBookMapPt: Record<string, string> = {
  Génesis: "Génesis",
  Êxodo: "Êxodo",
  Levítico: "Levítico",
  Números: "Números",
  Deuteronómio: "Deuteronómio",
  Josué: "Josué",
  Juízes: "Juízes",
  Rute: "Rute",
  "1 Samuel": "1 Samuel",
  "2 Samuel": "2 Samuel",
  "1 Reis": "1 Reis",
  "2 Reis": "2 Reis",
  "1 Crónicas": "1 Crónicas",
  "2 Crónicas": "2 Crónicas",
  Esdras: "Esdras",
  Neemias: "Neemias",
  Ester: "Ester",
  Jó: "Jó",
  Salmos: "Salmos",
  Provérbios: "Provérbios",
  Eclesiastes: "Eclesiastes",
  "Cântico de Salomão": "Cântico de Salomão",
  Isaías: "Isaías",
  Jeremias: "Jeremias",
  Lamentações: "Lamentações",
  Ezequiel: "Ezequiel",
  Daniel: "Daniel",
  Oseias: "Oseias",
  Joel: "Joel",
  Amós: "Amós",
  Obadias: "Obadias",
  Jonas: "Jonas",
  Miqueias: "Miqueias",
  Naum: "Naum",
  Habacuque: "Habacuque",
  Sofonias: "Sofonias",
  Ageu: "Ageu",
  Zacarias: "Zacarias",
  Malaquias: "Malaquias",
  Mateus: "Mateus",
  Marcos: "Marcos",
  Lucas: "Lucas",
  João: "João",
  Atos: "Atos",
  Romanos: "Romanos",
  "1 Coríntios": "1 Coríntios",
  "2 Coríntios": "2 Coríntios",
  Gálatas: "Gálatas",
  Efésios: "Efésios",
  Filipenses: "Filipenses",
  Colossenses: "Colossenses",
  "1 Tessalonicenses": "1 Tessalonicenses",
  "2 Tessalonicenses": "2 Tessalonicenses",
  "1 Timóteo": "1 Timóteo",
  "2 Timóteo": "2 Timóteo",
  Tito: "Tito",
  Filémon: "Filémon",
  Hebreus: "Hebreus",
  Tiago: "Tiago",
  "1 Pedro": "1 Pedro",
  "2 Pedro": "2 Pedro",
  "1 João": "1 João",
  "2 João": "2 João",
  "3 João": "3 João",
  Judas: "Judas",
  Apocalipse: "Apocalipse",
  Gén: "Génesis",
  Êx: "Êxodo",
  Le: "Levítico",
  Núm: "Números",
  De: "Deuteronómio",
  Jos: "Josué",
  Jz: "Juízes",
  Ru: "Rute",
  "1Sa": "1 Samuel",
  "2Sa": "2 Samuel",
  "1Rs": "1 Reis",
  "2Rs": "2 Reis",
  "1Cr": "1 Crónicas",
  "2Cr": "2 Crónicas",
  Esd: "Esdras",
  Ne: "Neemias",
  Est: "Ester",
  Sal: "Salmos",
  Pr: "Provérbios",
  Ec: "Eclesiastes",
  Cân: "Cântico de Salomão",
  Is: "Isaías",
  Je: "Jeremias",
  La: "Lamentações",
  Ez: "Ezequiel",
  Da: "Daniel",
  Os: "Oseias",
  Jl: "Joel",
  Am: "Amós",
  Ob: "Obadias",
  Jon: "Jonas",
  Miq: "Miqueias",
  Na: "Naum",
  Hab: "Habacuque",
  Sof: "Sofonias",
  Ag: "Ageu",
  Za: "Zacarias",
  Mal: "Malaquias",
  Mt: "Mateus",
  Mr: "Marcos",
  Lu: "Lucas",
  Jo: "João",
  At: "Atos",
  Ro: "Romanos",
  "1Co": "1 Coríntios",
  "2Co": "2 Coríntios",
  Gál: "Gálatas",
  Ef: "Efésios",
  Fil: "Filipenses",
  Col: "Colossenses",
  "1Te": "1 Tessalonicenses",
  "2Te": "2 Tessalonicenses",
  "1Ti": "1 Timóteo",
  "2Ti": "2 Timóteo",
  Tit: "Tito",
  Flm: "Filémon",
  He: "Hebreus",
  Tg: "Tiago",
  "1Pe": "1 Pedro",
  "2Pe": "2 Pedro",
  "1Jo": "1 João",
  "2Jo": "2 João",
  "3Jo": "3 João",
  Ju: "Judas",
  Ap: "Apocalipse",
};

export const bookNumberMapPt: Record<string, number> = {
  Génesis: 1,
  Êxodo: 2,
  Levítico: 3,
  Números: 4,
  Deuteronómio: 5,
  Josué: 6,
  Juízes: 7,
  Rute: 8,
  "1 Samuel": 9,
  "2 Samuel": 10,
  "1 Reis": 11,
  "2 Reis": 12,
  "1 Crónicas": 13,
  "2 Crónicas": 14,
  Esdras: 15,
  Neemias: 16,
  Ester: 17,
  Jó: 18,
  Salmos: 19,
  Provérbios: 20,
  Eclesiastes: 21,
  "Cântico de Salomão": 22,
  Isaías: 23,
  Jeremias: 24,
  Lamentações: 25,
  Ezequiel: 26,
  Daniel: 27,
  Oseias: 28,
  Joel: 29,
  Amós: 30,
  Obadias: 31,
  Jonas: 32,
  Miqueias: 33,
  Naum: 34,
  Habacuque: 35,
  Sofonias: 36,
  Ageu: 37,
  Zacarias: 38,
  Malaquias: 39,
  Mateus: 40,
  Marcos: 41,
  Lucas: 42,
  João: 43,
  Atos: 44,
  Romanos: 45,
  "1 Coríntios": 46,
  "2 Coríntios": 47,
  Gálatas: 48,
  Efésios: 49,
  Filipenses: 50,
  Colossenses: 51,
  "1 Tessalonicenses": 52,
  "2 Tessalonicenses": 53,
  "1 Timóteo": 54,
  "2 Timóteo": 55,
  Tito: 56,
  Filémon: 57,
  Hebreus: 58,
  Tiago: 59,
  "1 Pedro": 60,
  "2 Pedro": 61,
  "1 João": 62,
  "2 João": 63,
  "3 João": 64,
  Judas: 65,
  Apocalipse: 66,
};

export const singleChapterBooksPt: Set<string> = new Set([
  "Obadias",
  "Filémon",
  "2 João",
  "3 João",
  "Judas",
]);
