export const bibleBookMapDe: Record<string, string> = {
  "1. Mose (Genesis)": "1. Mose (Genesis)",
  "2. Mose (Exodus)": "2. Mose (Exodus)",
  "3. Mose (Levitikus)": "3. Mose (Levitikus)",
  "4. Mose (Numeri)": "4. Mose (Numeri)",
  "5. Mose (Deuteronomium)": "5. Mose (Deuteronomium)",
  Josua: "Josua",
  Richter: "Richter",
  Ruth: "Ruth",
  "1. Samuel": "1. Samuel",
  "2. Samuel": "2. Samuel",
  "1. Könige": "1. Könige",
  "2. Könige": "2. Könige",
  "1. Chronika": "1. Chronika",
  "2. Chronika": "2. Chronika",
  Esra: "Esra",
  Nehemia: "Nehemia",
  Esther: "Esther",
  Hiob: "Hiob",
  Psalmen: "Psalmen",
  Sprüche: "Sprüche",
  Prediger: "Prediger",
  "Hohes Lied": "Hohes Lied",
  Jesaja: "Jesaja",
  Jeremia: "Jeremia",
  Klagelieder: "Klagelieder",
  Hesekiel: "Hesekiel",
  Daniel: "Daniel",
  Hosea: "Hosea",
  Joel: "Joel",
  Amos: "Amos",
  Obadja: "Obadja",
  Jona: "Jona",
  Micha: "Micha",
  Nahum: "Nahum",
  Habakuk: "Habakuk",
  Zephanja: "Zephanja",
  Haggai: "Haggai",
  Sacharja: "Sacharja",
  Maleachi: "Maleachi",
  Matthäus: "Matthäus",
  Markus: "Markus",
  Lukas: "Lukas",
  Johannes: "Johannes",
  Apostelgeschichte: "Apostelgeschichte",
  Römer: "Römer",
  "1. Korinther": "1. Korinther",
  "2. Korinther": "2. Korinther",
  Galater: "Galater",
  Epheser: "Epheser",
  Philipper: "Philipper",
  Kolosser: "Kolosser",
  "1. Thessalonicher": "1. Thessalonicher",
  "2. Thessalonicher": "2. Thessalonicher",
  "1. Timotheus": "1. Timotheus",
  "2. Timotheus": "2. Timotheus",
  Titus: "Titus",
  Philemon: "Philemon",
  Hebräer: "Hebräer",
  Jakobus: "Jakobus",
  "1. Petrus": "1. Petrus",
  "2. Petrus": "2. Petrus",
  "1. Johannes": "1. Johannes",
  "2. Johannes": "2. Johannes",
  "3. Johannes": "3. Johannes",
  Judas: "Judas",
  Offenbarung: "Offenbarung",
  "1Mo": "1. Mose (Genesis)",
  "2Mo": "2. Mose (Exodus)",
  "3Mo": "3. Mose (Levitikus)",
  "4Mo": "4. Mose (Numeri)",
  "5Mo": "5. Mose (Deuteronomium)",
  Jos: "Josua",
  Ri: "Richter",
  Ru: "Ruth",
  "1Sa": "1. Samuel",
  "2Sa": "2. Samuel",
  "1Kö": "1. Könige",
  "2Kö": "2. Könige",
  "1Ch": "1. Chronika",
  "2Ch": "2. Chronika",
  Esr: "Esra",
  Ne: "Nehemia",
  Est: "Esther",
  Hi: "Hiob",
  Ps: "Psalmen",
  Spr: "Sprüche",
  Pr: "Prediger",
  Hoh: "Hohes Lied",
  Jes: "Jesaja",
  Jer: "Jeremia",
  Klg: "Klagelieder",
  Hes: "Hesekiel",
  Da: "Daniel",
  Hos: "Hosea",
  Am: "Amos",
  Ob: "Obadja",
  Jon: "Jona",
  Mi: "Micha",
  Nah: "Nahum",
  Hab: "Habakuk",
  Ze: "Zephanja",
  Hag: "Haggai",
  Sach: "Sacharja",
  Mal: "Maleachi",
  Mat: "Matthäus",
  Mar: "Markus",
  Luk: "Lukas",
  Joh: "Johannes",
  Apg: "Apostelgeschichte",
  Rö: "Römer",
  "1Ko": "1. Korinther",
  "2Ko": "2. Korinther",
  Gal: "Galater",
  Eph: "Epheser",
  Php: "Philipper",
  Kol: "Kolosser",
  "1Th": "1. Thessalonicher",
  "2Th": "2. Thessalonicher",
  "1Ti": "1. Timotheus",
  "2Ti": "2. Timotheus",
  Tit: "Titus",
  Phm: "Philemon",
  Heb: "Hebräer",
  Jak: "Jakobus",
  "1Pe": "1. Petrus",
  "2Pe": "2. Petrus",
  "1Jo": "1. Johannes",
  "2Jo": "2. Johannes",
  "3Jo": "3. Johannes",
  Jud: "Judas",
  Off: "Offenbarung",
};

export const bookNumberMapDe: Record<string, number> = {
  "1. Mose (Genesis)": 1,
  "2. Mose (Exodus)": 2,
  "3. Mose (Levitikus)": 3,
  "4. Mose (Numeri)": 4,
  "5. Mose (Deuteronomium)": 5,
  Josua: 6,
  Richter: 7,
  Ruth: 8,
  "1. Samuel": 9,
  "2. Samuel": 10,
  "1. Könige": 11,
  "2. Könige": 12,
  "1. Chronika": 13,
  "2. Chronika": 14,
  Esra: 15,
  Nehemia: 16,
  Esther: 17,
  Hiob: 18,
  Psalmen: 19,
  Sprüche: 20,
  Prediger: 21,
  "Hohes Lied": 22,
  Jesaja: 23,
  Jeremia: 24,
  Klagelieder: 25,
  Hesekiel: 26,
  Daniel: 27,
  Hosea: 28,
  Joel: 29,
  Amos: 30,
  Obadja: 31,
  Jona: 32,
  Micha: 33,
  Nahum: 34,
  Habakuk: 35,
  Zephanja: 36,
  Haggai: 37,
  Sacharja: 38,
  Maleachi: 39,
  Matthäus: 40,
  Markus: 41,
  Lukas: 42,
  Johannes: 43,
  Apostelgeschichte: 44,
  Römer: 45,
  "1. Korinther": 46,
  "2. Korinther": 47,
  Galater: 48,
  Epheser: 49,
  Philipper: 50,
  Kolosser: 51,
  "1. Thessalonicher": 52,
  "2. Thessalonicher": 53,
  "1. Timotheus": 54,
  "2. Timotheus": 55,
  Titus: 56,
  Philemon: 57,
  Hebräer: 58,
  Jakobus: 59,
  "1. Petrus": 60,
  "2. Petrus": 61,
  "1. Johannes": 62,
  "2. Johannes": 63,
  "3. Johannes": 64,
  Judas: 65,
  Offenbarung: 66,
};

export const singleChapterBooksDe: Set<string> = new Set([
  "Obadja",
  "Philemon",
  "2. Johannes",
  "3. Johannes",
  "Judas",
]);
