export const bibleBookMapEs: Record<string, string> = {
  Gen: "Génesis",
  Gén: "Génesis",
  Génesis: "Génesis",
  Éx: "Éxodo",
  Ex: "Éxodo",
  Éxo: "Éxodo",
  Éxodo: "Éxodo",
  Lev: "Levítico",
  Levítico: "Levítico",
  Num: "Números",
  Núm: "Números",
  Números: "Números",
  Dt: "Deuteronomio",
  Deut: "Deuteronomio",
  Deuteronomio: "Deuteronomio",
  Jos: "Josué",
  Josué: "Josué",
  Jue: "Jueces",
  Juec: "Jueces",
  Jueces: "Jueces",
  Rut: "Rut",
  "1 S": "1 Samuel",
  "1 Sam": "1 Samuel",
  "1 Samuel": "1 Samuel",
  "2 S": "2 Samuel",
  "2 Sam": "2 Samuel",
  "2 Samuel": "2 Samuel",
  "1 R": "1 Reyes",
  "1 Rey": "1 Reyes",
  "1 Reyes": "1 Reyes",
  "2 R": "2 Reyes",
  "2 Rey": "2 Reyes",
  "2 Reyes": "2 Reyes",
  "1 Cr": "1 Crónicas",
  "1 Cró": "1 Crónicas",
  "1 Crónicas": "1 Crónicas",
  "2 Cr": "2 Crónicas",
  "2 Cró": "2 Crónicas",
  "2 Crónicas": "2 Crónicas",
  Esd: "Esdras",
  Esdras: "Esdras",
  Neh: "Nehemías",
  Nehemías: "Nehemías",
  Est: "Ester",
  Ester: "Ester",
  Job: "Job",
  Sal: "Salmos",
  Salm: "Salmos",
  Salmos: "Salmos",
  Pro: "Proverbios",
  Prov: "Proverbios",
  Proverbios: "Proverbios",
  Ecl: "Eclesiastés",
  Ecle: "Eclesiastés",
  Eclesiastés: "Eclesiastés",
  Cant: "Cantar de los Cantares",
  Cnt: "Cantar de los Cantares",
  "Cantar de los Cantares": "Cantar de los Cantares",
  "El Cantar de los Cantares": "Cantar de los Cantares",
  Isa: "Isaías",
  Isaías: "Isaías",
  Jer: "Jeremías",
  Jeremías: "Jeremías",
  Lam: "Lamentaciones",
  Lamentaciones: "Lamentaciones",
  Ez: "Ezequiel",
  Ezeq: "Ezequiel",
  Ezequiel: "Ezequiel",
  Dan: "Daniel",
  Daniel: "Daniel",
  Ose: "Oseas",
  Oseas: "Oseas",
  Joel: "Joel",
  Amós: "Amós",
  Abd: "Abdías",
  Abdías: "Abdías",
  Jon: "Jonás",
  Jonás: "Jonás",
  Miq: "Miqueas",
  Miqueas: "Miqueas",
  Nah: "Nahúm",
  Nahúm: "Nahúm",
  Hab: "Habacuc",
  Habacuc: "Habacuc",
  Sof: "Sofonías",
  Sofonías: "Sofonías",
  Hag: "Hageo",
  Ageo: "Hageo",
  Zac: "Zacarías",
  Zacarías: "Zacarías",
  Mal: "Malaquías",
  Malaquías: "Malaquías",
  Mat: "Mateo",
  Mt: "Mateo",
  Mateo: "Mateo",
  Mar: "Marcos",
  Mr: "Marcos",
  Marcos: "Marcos",
  Luc: "Lucas",
  Lc: "Lucas",
  Lucas: "Lucas",
  Jn: "Juan",
  Juan: "Juan",
  Hech: "Hechos",
  Hch: "Hechos",
  Hechos: "Hechos",
  Rom: "Romanos",
  Ro: "Romanos",
  Romanos: "Romanos",
  "1 Cor": "1 Corintios",
  "1 Co": "1 Corintios",
  "1 Corintios": "1 Corintios",
  "2 Cor": "2 Corintios",
  "2 Co": "2 Corintios",
  "2 Corintios": "2 Corintios",
  Gal: "Gálatas",
  Gál: "Gálatas",
  Gálatas: "Gálatas",
  Ef: "Efesios",
  Efes: "Efesios",
  Efesios: "Efesios",
  Fil: "Filipenses",
  Filip: "Filipenses",
  Filipenses: "Filipenses",
  Col: "Colosenses",
  Colosenses: "Colosenses",
  "1 Tes": "1 Tesalonicenses",
  "1 Th": "1 Tesalonicenses",
  "1 Tesalonicenses": "1 Tesalonicenses",
  "2 Tes": "2 Tesalonicenses",
  "2 Th": "2 Tesalonicenses",
  "2 Tesalonicenses": "2 Tesalonicenses",
  "1 Tim": "1 Timoteo",
  "1 Ti": "1 Timoteo",
  "1 Timoteo": "1 Timoteo",
  "2 Tim": "2 Timoteo",
  "2 Ti": "2 Timoteo",
  "2 Timoteo": "2 Timoteo",
  Tit: "Tito",
  Tito: "Tito",
  Flm: "Filemón",
  Filem: "Filemón",
  Filemón: "Filemón",
  Heb: "Hebreos",
  Hebreos: "Hebreos",
  Sant: "Santiago",
  Stg: "Santiago",
  Santiago: "Santiago",
  "1 Ped": "1 Pedro",
  "1 Pe": "1 Pedro",
  "1 Pedro": "1 Pedro",
  "2 Ped": "2 Pedro",
  "2 Pe": "2 Pedro",
  "2 Pedro": "2 Pedro",
  "1 Jn": "1 Juan",
  "1 Juan": "1 Juan",
  "2 Jn": "2 Juan",
  "2 Juan": "2 Juan",
  "3 Jn": "3 Juan",
  "3 Juan": "3 Juan",
  Jud: "Judas",
  Judas: "Judas",
  Rev: "Revelación",
  Apoc: "Revelación",
  Ap: "Revelación",
  Apocalipsis: "Revelación",
  Revelación: "Revelación",
};

export const bookNumberMapEs: Record<string, number> = {
  Génesis: 1,
  Éxodo: 2,
  Levítico: 3,
  Números: 4,
  Deuteronomio: 5,
  Josué: 6,
  Jueces: 7,
  Rut: 8,
  "1 Samuel": 9,
  "2 Samuel": 10,
  "1 Reyes": 11,
  "2 Reyes": 12,
  "1 Crónicas": 13,
  "2 Crónicas": 14,
  Esdras: 15,
  Nehemías: 16,
  Ester: 17,
  Job: 18,
  Salmos: 19,
  Proverbios: 20,
  Eclesiastés: 21,
  "El Cantar de los Cantares": 22,
  Isaías: 23,
  Jeremías: 24,
  Lamentaciones: 25,
  Ezequiel: 26,
  Daniel: 27,
  Oseas: 28,
  Joel: 29,
  Amós: 30,
  Abdías: 31,
  Jonás: 32,
  Miqueas: 33,
  Nahúm: 34,
  Habacuc: 35,
  Sofonías: 36,
  Ageo: 37,
  Zacarías: 38,
  Malaquías: 39,
  Mateo: 40,
  Marcos: 41,
  Lucas: 42,
  Juan: 43,
  Hechos: 44,
  Romanos: 45,
  "1 Corintios": 46,
  "2 Corintios": 47,
  Gálatas: 48,
  Efesios: 49,
  Filipenses: 50,
  Colosenses: 51,
  "1 Tesalonicenses": 52,
  "2 Tesalonicenses": 53,
  "1 Timoteo": 54,
  "2 Timoteo": 55,
  Tito: 56,
  Filemón: 57,
  Hebreos: 58,
  Santiago: 59,
  "1 Pedro": 60,
  "2 Pedro": 61,
  "1 Juan": 62,
  "2 Juan": 63,
  "3 Juan": 64,
  Judas: 65,
  Apocalipsis: 66,
};

export const singleChapterBooksEs: Set<string> = new Set([
  "Abdías",
  "Filemón",
  "2 Juan",
  "3 Juan",
  "Judas",
]);
