// src/bibleBooks.ts

export const bibleBookMap: Record<string, string> = {
    'Genesis': 'Genesis',
    'Ge': 'Genesis',
    'Exodus': 'Exodus',
    'Ex': 'Exodus',
    'Leviticus': 'Leviticus',
    'Lev': 'Leviticus',
    'Numbers': 'Numbers',
    'Nu': 'Numbers',
    'Deuteronomy': 'Deuteronomy',
    'Dt': 'Deuteronomy',
    'Joshua': 'Joshua',
    'Jos': 'Joshua',
    'Judges': 'Judges',
    'Jdg': 'Judges',
    'Ruth': 'Ruth',
    'Ru': 'Ruth',
    '1 Samuel': '1 Samuel',
    '1 Sa': '1 Samuel',
    '2 Samuel': '2 Samuel',
    '2 Sa': '2 Samuel',
    '1 Kings': '1 Kings',
    '1 Ki': '1 Kings',
    '2 Kings': '2 Kings',
    '2 Ki': '2 Kings',
    '1 Chronicles': '1 Chronicles',
    '1 Ch': '1 Chronicles',
    '2 Chronicles': '2 Chronicles',
    '2 Ch': '2 Chronicles',
    'Ezra': 'Ezra',
    'Nehemiah': 'Nehemiah',
    'Esther': 'Esther',
    'Job': 'Job',
    'Psalms': 'Psalms',
    'Ps': 'Psalms',
    'Psalm': 'Psalms',
    'Proverbs': 'Proverbs',
    'Pr': 'Proverbs',
    'Ecclesiastes': 'Ecclesiastes',
    'Ecc': 'Ecclesiastes',
    'Song of Solomon': 'Song of Solomon',
    'So': 'Song of Solomon',
    'Isaiah': 'Isaiah',
    'Is': 'Isaiah',
    'Jeremiah': 'Jeremiah',
    'Je': 'Jeremiah',
    'Lamentations': 'Lamentations',
    'La': 'Lamentations',
    'Ezekiel': 'Ezekiel',
    'Eze': 'Ezekiel',
    'Daniel': 'Daniel',
    'Da': 'Daniel',
    'Hosea': 'Hosea',
    'Ho': 'Hosea',
    'Joel': 'Joel',
    'Amos': 'Amos',
    'Obadiah': 'Obadiah',
    'Jonah': 'Jonah',
    'Micah': 'Micah',
    'Nahum': 'Nahum',
    'Habakkuk': 'Habakkuk',
    'Zephaniah': 'Zephaniah',
    'Haggai': 'Haggai',
    'Zechariah': 'Zechariah',
    'Malachi': 'Malachi',
    'Matthew': 'Matthew',
    'Mt': 'Matthew',
    'Mark': 'Mark',
    'Mr': 'Mark',
    'Luke': 'Luke',
    'Lk': 'Luke',
    'John': 'John',
    'Jn': 'John',
    'Acts': 'Acts',
    'Ac': 'Acts',
    'Romans': 'Romans',
    'Ro': 'Romans',
    '1 Corinthians': '1 Corinthians',
    '1 Co': '1 Corinthians',
    '2 Corinthians': '2 Corinthians',
    '2 Co': '2 Corinthians',
    'Galatians': 'Galatians',
    'Ga': 'Galatians',
    'Ephesians': 'Ephesians',
    'Eph': 'Ephesians',
    'Philippians': 'Philippians',
    'Php': 'Philippians',
    'Colossians': 'Colossians',
    'Col': 'Colossians',
    '1 Thessalonians': '1 Thessalonians',
    '1 Th': '1 Thessalonians',
    '2 Thessalonians': '2 Thessalonians',
    '2 Th': '2 Thessalonians',
    '1 Timothy': '1 Timothy',
    '1 Ti': '1 Timothy',
    '2 Timothy': '2 Timothy',
    '2 Ti': '2 Timothy',
    'Titus': 'Titus',
    'Philemon': 'Philemon',
    'Hebrews': 'Hebrews',
    'James': 'James',
    '1 Peter': '1 Peter',
    '2 Peter': '2 Peter',
    '1 John': '1 John',
    '2 John': '2 John',
    '3 John': '3 John',
    'Jude': 'Jude',
    'Revelation': 'Revelation',
    'Re': 'Revelation',
    'Rev': 'Revelation',
};


export const bookNumberMap: Record<string, number> = {
    "Genesis": 1,
    "Exodus": 2,
    "Leviticus": 3,
    "Numbers": 4,
    "Deuteronomy": 5,
    "Joshua": 6,
    "Judges": 7,
    "Ruth": 8,
    "1 Samuel": 9,
    "2 Samuel": 10,
    "1 Kings": 11,
    "2 Kings": 12,
    "1 Chronicles": 13,
    "2 Chronicles": 14,
    "Ezra": 15,
    "Nehemiah": 16,
    "Esther": 17,
    "Job": 18,
    "Psalms": 19,
    "Proverbs": 20,
    "Ecclesiastes": 21,
    "Song of Solomon": 22,
    "Isaiah": 23,
    "Jeremiah": 24,
    "Lamentations": 25,
    "Ezekiel": 26,
    "Daniel": 27,
    "Hosea": 28,
    "Joel": 29,
    "Amos": 30,
    "Obadiah": 31,
    "Jonah": 32,
    "Micah": 33,
    "Nahum": 34,
    "Habakkuk": 35,
    "Zephaniah": 36,
    "Haggai": 37,
    "Zechariah": 38,
    "Malachi": 39,
    "Matthew": 40,
    "Mark": 41,
    "Luke": 42,
    "John": 43,
    "Acts": 44,
    "Romans": 45,
    "1 Corinthians": 46,
    "2 Corinthians": 47,
    "Galatians": 48,
    "Ephesians": 49,
    "Philippians": 50,
    "Colossians": 51,
    "1 Thessalonians": 52,
    "2 Thessalonians": 53,
    "1 Timothy": 54,
    "2 Timothy": 55,
    "Titus": 56,
    "Philemon": 57,
    "Hebrews": 58,
    "James": 59,
    "1 Peter": 60,
    "2 Peter": 61,
    "1 John": 62,
    "2 John": 63,
    "3 John": 64,
    "Jude": 65,
    "Revelation": 66
  }
  
