export const bibleBookMapNo: Record<string, string> = {
  // Det gamle testamentet
  "1. Mosebok": "1. Mosebok",
  "1 Mos": "1. Mosebok",
  "2. Mosebok": "2. Mosebok",
  "2 Mos": "2. Mosebok",
  "3. Mosebok": "3. Mosebok",
  "3 Mos": "3. Mosebok",
  "4. Mosebok": "4. Mosebok",
  "4 Mos": "4. Mosebok",
  "5. Mosebok": "5. Mosebok",
  "5 Mos": "5. Mosebok",
  Josva: "Josva",
  Jos: "Josva",
  Dommerne: "Dommerne",
  Dom: "Dommerne",
  Rut: "Rut",
  "1. Samuelsbok": "1. Samuelsbok",
  "1 Sa": "1. Samuelsbok",
  "1 Sam": "1. Samuelsbok",
  "2. Samuelsbok": "2. Samuelsbok",
  "2 Sa": "2. Samuelsbok",
  "2 Sam": "2. Samuelsbok",
  "1. Kongebok": "1. Kongebok",
  "1 Kg": "1. Kongebok",
  "2. Kongebok": "2. Kongebok",
  "2 Kg": "2. Kongebok",
  "1. Krønikebok": "1. Krønikebok",
  "1 Kr": "1. Krønikebok",
  "2. Krønikebok": "2. Krønikebok",
  "2 Kr": "2. Krønikebok",
  Esra: "Esra",
  Esr: "Esra",
  Nehemja: "Nehemja",
  Ne: "Nehemja",
  Ester: "Ester",
  Est: "Ester",
  Job: "Job",
  Salmene: "Salmene",
  Sl: "Salmene",
  Ordspråkene: "Ordspråkene",
  Ord: "Ordspråkene",
  Forkynneren: "Forkynneren",
  For: "Forkynneren",
  Høysangen: "Høysangen",
  Høy: "Høysangen",
  Jesaja: "Jesaja",
  Jes: "Jesaja",
  Jeremia: "Jeremia",
  Jer: "Jeremia",
  Klagesangene: "Klagesangene",
  Kla: "Klagesangene",
  Esekiel: "Esekiel",
  Ese: "Esekiel",
  Daniel: "Daniel",
  Da: "Daniel",
  Hosea: "Hosea",
  Ho: "Hosea",
  Joel: "Joel",
  Joe: "Joel",
  Amos: "Amos",
  Am: "Amos",
  Obadja: "Obadja",
  Ob: "Obadja",
  Jona: "Jona",
  Jon: "Jona",
  Mika: "Mika",
  Mi: "Mika",
  Nahum: "Nahum",
  Na: "Nahum",
  Habakkuk: "Habakkuk",
  Hab: "Habakkuk",
  Sefanja: "Sefanja",
  Sef: "Sefanja",
  Haggai: "Haggai",
  Hag: "Haggai",
  Sakarja: "Sakarja",
  Sak: "Sakarja",
  Malaki: "Malaki",
  Mal: "Malaki",

  // Det nye testamentet
  Matteus: "Matteus",
  Mt: "Matteus",
  Markus: "Markus",
  Mr: "Markus",
  Lukas: "Lukas",
  Lu: "Lukas",
  Johannes: "Johannes",
  Joh: "Johannes",
  "Apostlenes gjerninger": "Apostlenes gjerninger",
  Apg: "Apostlenes gjerninger",
  Romerne: "Romerne",
  Ro: "Romerne",
  "1. Korinter": "1. Korinter",
  "1 Kt": "1. Korinter",
  "2. Korinter": "2. Korinter",
  "2 Kt": "2. Korinter",
  Galaterne: "Galaterne",
  Ga: "Galaterne",
  Efeserne: "Efeserne",
  Ef: "Efeserne",
  Filipperne: "Filipperne",
  Flp: "Filipperne",
  Kolosserne: "Kolosserne",
  Kol: "Kolosserne",
  "1. Tessaloniker": "1. Tessaloniker",
  "1 Te": "1. Tessaloniker",
  "2. Tessaloniker": "2. Tessaloniker",
  "2 Te": "2. Tessaloniker",
  "1. Timoteus": "1. Timoteus",
  "1 Ti": "1. Timoteus",
  "2. Timoteus": "2. Timoteus",
  "2 Ti": "2. Timoteus",
  Titus: "Titus",
  Tit: "Titus",
  Filemon: "Filemon",
  Flm: "Filemon",
  Hebreerne: "Hebreerne",
  He: "Hebreerne",
  Jakob: "Jakob",
  Jak: "Jakob",
  "1. Peter": "1. Peter",
  "1 Pe": "1. Peter",
  "2. Peter": "2. Peter",
  "2 Pe": "2. Peter",
  "1. Johannes": "1. Johannes",
  "1 Jo": "1. Johannes",
  "2. Johannes": "2. Johannes",
  "2 Jo": "2. Johannes",
  "3. Johannes": "3. Johannes",
  "3 Jo": "3. Johannes",
  Judas: "Judas",
  Jud: "Judas",
  Åpenbaringen: "Åpenbaringen",
  Åp: "Åpenbaringen",
};

export const bookNumberMapNo: Record<string, number> = {
  // Det gamle testamentet
  "1. Mosebok": 1,
  "2. Mosebok": 2,
  "3. Mosebok": 3,
  "4. Mosebok": 4,
  "5. Mosebok": 5,
  Josva: 6,
  Dommerne: 7,
  Rut: 8,
  "1. Samuelsbok": 9,
  "2. Samuelsbok": 10,
  "1. Kongebok": 11,
  "2. Kongebok": 12,
  "1. Krønikebok": 13,
  "2. Krønikebok": 14,
  Esra: 15,
  Nehemja: 16,
  Ester: 17,
  Job: 18,
  Salmene: 19,
  Ordspråkene: 20,
  Forkynneren: 21,
  Høysangen: 22,
  Jesaja: 23,
  Jeremia: 24,
  Klagesangene: 25,
  Esekiel: 26,
  Daniel: 27,
  Hosea: 28,
  Joel: 29,
  Amos: 30,
  Obadja: 31,
  Jona: 32,
  Mika: 33,
  Nahum: 34,
  Habakkuk: 35,
  Sefanja: 36,
  Haggai: 37,
  Sakarja: 38,
  Malaki: 39,

  // Det nye testamentet
  Matteus: 40,
  Markus: 41,
  Lukas: 42,
  Johannes: 43,
  "Apostlenes gjerninger": 44,
  Romerne: 45,
  "1. Korinter": 46,
  "2. Korinter": 47,
  Galaterne: 48,
  Efeserne: 49,
  Filipperne: 50,
  Kolosserne: 51,
  "1. Tessaloniker": 52,
  "2. Tessaloniker": 53,
  "1. Timoteus": 54,
  "2. Timoteus": 55,
  Titus: 56,
  Filemon: 57,
  Hebreerne: 58,
  Jakob: 59,
  "1. Peter": 60,
  "2. Peter": 61,
  "1. Johannes": 62,
  "2. Johannes": 63,
  "3. Johannes": 64,
  Judas: 65,
  Åpenbaringen: 66,
};

export const singleChapterBooksNo: Set<string> = new Set([
  "Obadja",
  "Filemon",
  "2. Johannes",
  "3. Johannes",
  "Judas",
]);
